export type ResumeTemplate = {
  id: string;
  name: string;
  category: string;
  layout: "single" | "sidebar" | "split";
  style: "minimal" | "modern" | "classic" | "bold" | "creative";
  accent: string;
};

export const resumeTemplates: ResumeTemplate[] = [
  // 01–05 — Classic
  {
    id: "classic-centered",
    name: "Classic Centered",
    category: "Classic",
    layout: "single",
    style: "classic",
    accent: "#171717",
  },
  {
    id: "classic-left",
    name: "Classic Left",
    category: "Classic",
    layout: "single",
    style: "classic",
    accent: "#374151",
  },
  {
    id: "classic-rule",
    name: "Classic Rule",
    category: "Classic",
    layout: "single",
    style: "classic",
    accent: "#1f2937",
  },
  {
    id: "classic-formal",
    name: "Classic Formal",
    category: "Classic",
    layout: "single",
    style: "classic",
    accent: "#111827",
  },
  {
    id: "classic-serif",
    name: "Classic Serif",
    category: "Classic",
    layout: "single",
    style: "classic",
    accent: "#292524",
  },

  // 06–10 — Modern
  {
    id: "modern-header",
    name: "Modern Header",
    category: "Modern",
    layout: "single",
    style: "modern",
    accent: "#1e3a5f",
  },
  {
    id: "modern-blocks",
    name: "Modern Blocks",
    category: "Modern",
    layout: "single",
    style: "modern",
    accent: "#334155",
  },
  {
    id: "modern-lines",
    name: "Modern Lines",
    category: "Modern",
    layout: "single",
    style: "modern",
    accent: "#475569",
  },
  {
    id: "modern-spaced",
    name: "Modern Spaced",
    category: "Modern",
    layout: "single",
    style: "modern",
    accent: "#1f2937",
  },
  {
    id: "modern-grid",
    name: "Modern Grid",
    category: "Modern",
    layout: "split",
    style: "modern",
    accent: "#1e293b",
  },

  // 11–15 — Executive
  {
    id: "executive-black",
    name: "Executive Black",
    category: "Executive",
    layout: "single",
    style: "bold",
    accent: "#111111",
  },
  {
    id: "executive-navy",
    name: "Executive Navy",
    category: "Executive",
    layout: "single",
    style: "bold",
    accent: "#172554",
  },
  {
    id: "executive-bar",
    name: "Executive Bar",
    category: "Executive",
    layout: "sidebar",
    style: "bold",
    accent: "#1c1917",
  },
  {
    id: "executive-columns",
    name: "Executive Columns",
    category: "Executive",
    layout: "split",
    style: "bold",
    accent: "#292524",
  },
  {
    id: "executive-profile",
    name: "Executive Profile",
    category: "Executive",
    layout: "sidebar",
    style: "bold",
    accent: "#262626",
  },

  // 16–20 — Minimal
  {
    id: "minimal-air",
    name: "Minimal Air",
    category: "Minimal",
    layout: "single",
    style: "minimal",
    accent: "#262626",
  },
  {
    id: "minimal-clean",
    name: "Minimal Clean",
    category: "Minimal",
    layout: "single",
    style: "minimal",
    accent: "#374151",
  },
  {
    id: "minimal-thin",
    name: "Minimal Thin",
    category: "Minimal",
    layout: "single",
    style: "minimal",
    accent: "#475569",
  },
  {
    id: "minimal-mono",
    name: "Minimal Mono",
    category: "Minimal",
    layout: "single",
    style: "minimal",
    accent: "#18181b",
  },
  {
    id: "minimal-tight",
    name: "Minimal Tight",
    category: "Minimal",
    layout: "single",
    style: "minimal",
    accent: "#333333",
  },

  // 21–25 — Sidebar
  {
    id: "sidebar-dark",
    name: "Dark Sidebar",
    category: "Sidebar",
    layout: "sidebar",
    style: "bold",
    accent: "#172554",
  },
  {
    id: "sidebar-slate",
    name: "Slate Sidebar",
    category: "Sidebar",
    layout: "sidebar",
    style: "modern",
    accent: "#334155",
  },
  {
    id: "sidebar-forest",
    name: "Forest Sidebar",
    category: "Sidebar",
    layout: "sidebar",
    style: "creative",
    accent: "#14532d",
  },
  {
    id: "sidebar-charcoal",
    name: "Charcoal Sidebar",
    category: "Sidebar",
    layout: "sidebar",
    style: "bold",
    accent: "#292524",
  },
  {
    id: "sidebar-light",
    name: "Light Sidebar",
    category: "Sidebar",
    layout: "sidebar",
    style: "minimal",
    accent: "#475569",
  },

  // 26–30 — Two Column
  {
    id: "columns-balanced",
    name: "Balanced Columns",
    category: "Two Column",
    layout: "split",
    style: "modern",
    accent: "#334155",
  },
  {
    id: "columns-skills",
    name: "Skills First",
    category: "Two Column",
    layout: "split",
    style: "modern",
    accent: "#1e3a5f",
  },
  {
    id: "columns-experience",
    name: "Experience First",
    category: "Two Column",
    layout: "split",
    style: "classic",
    accent: "#374151",
  },
  {
    id: "columns-narrow",
    name: "Narrow Profile",
    category: "Two Column",
    layout: "split",
    style: "minimal",
    accent: "#262626",
  },
  {
    id: "columns-wide",
    name: "Wide Profile",
    category: "Two Column",
    layout: "split",
    style: "bold",
    accent: "#1f2937",
  },

  // 31–35 — Developer
  {
    id: "developer-terminal",
    name: "Developer Terminal",
    category: "Developer",
    layout: "sidebar",
    style: "modern",
    accent: "#14532d",
  },
  {
    id: "developer-clean",
    name: "Developer Clean",
    category: "Developer",
    layout: "single",
    style: "minimal",
    accent: "#1f2937",
  },
  {
    id: "developer-stack",
    name: "Developer Stack",
    category: "Developer",
    layout: "split",
    style: "modern",
    accent: "#334155",
  },
  {
    id: "developer-pro",
    name: "Developer Pro",
    category: "Developer",
    layout: "sidebar",
    style: "bold",
    accent: "#1e293b",
  },
  {
    id: "developer-dark",
    name: "Developer Dark",
    category: "Developer",
    layout: "sidebar",
    style: "creative",
    accent: "#18181b",
  },

  // 36–40 — Student / Entry Level
  {
    id: "student-simple",
    name: "Student Simple",
    category: "Student",
    layout: "single",
    style: "minimal",
    accent: "#374151",
  },
  {
    id: "student-modern",
    name: "Student Modern",
    category: "Student",
    layout: "single",
    style: "modern",
    accent: "#1e3a5f",
  },
  {
    id: "student-sidebar",
    name: "Student Sidebar",
    category: "Student",
    layout: "sidebar",
    style: "modern",
    accent: "#475569",
  },
  {
    id: "student-columns",
    name: "Student Columns",
    category: "Student",
    layout: "split",
    style: "minimal",
    accent: "#334155",
  },
  {
    id: "student-formal",
    name: "Student Formal",
    category: "Student",
    layout: "single",
    style: "classic",
    accent: "#1f2937",
  },

  // 41–45 — Academic
  {
    id: "academic-classic",
    name: "Academic Classic",
    category: "Academic",
    layout: "single",
    style: "classic",
    accent: "#1e293b",
  },
  {
    id: "academic-research",
    name: "Academic Research",
    category: "Academic",
    layout: "single",
    style: "minimal",
    accent: "#334155",
  },
  {
    id: "academic-sidebar",
    name: "Academic Sidebar",
    category: "Academic",
    layout: "sidebar",
    style: "classic",
    accent: "#475569",
  },
  {
    id: "academic-two-column",
    name: "Academic Columns",
    category: "Academic",
    layout: "split",
    style: "classic",
    accent: "#292524",
  },
  {
    id: "academic-formal",
    name: "Academic Formal",
    category: "Academic",
    layout: "single",
    style: "bold",
    accent: "#111827",
  },

  // 46–50 — ATS / Professional
  {
    id: "ats-standard",
    name: "ATS Standard",
    category: "ATS",
    layout: "single",
    style: "minimal",
    accent: "#111111",
  },
  {
    id: "ats-clean",
    name: "ATS Clean",
    category: "ATS",
    layout: "single",
    style: "minimal",
    accent: "#222222",
  },
  {
    id: "ats-professional",
    name: "ATS Professional",
    category: "ATS",
    layout: "single",
    style: "classic",
    accent: "#333333",
  },
  {
    id: "ats-modern",
    name: "ATS Modern",
    category: "ATS",
    layout: "single",
    style: "modern",
    accent: "#1f2937",
  },
  {
    id: "ats-executive",
    name: "ATS Executive",
    category: "ATS",
    layout: "single",
    style: "bold",
    accent: "#292524",
  },
];